name: Auto Merge

on:
  pull_request:

jobs:

  auto-merge:
    name: Auto Merge
    runs-on: ubuntu-latest

    steps:
      - uses: ocean90/gh-action-auto-merge-dependency-updates@feature/auto-merge
        with:
          github-token: ${{secrets.SCRIPT_TOKEN}}
          allowed-update-types: 'devDependencies:minor, devDependencies:patch, dependencies:minor, dependencies:patch'
