name: Auto Merge

on:
  pull_request:

jobs:

  auto-merge:
    name: Auto Merge
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v3
        with:
          debug: true
          script: |
            const mutation = `mutation($pullRequestId:ID!) {
                enablePullRequestAutoMerge(input: {pullRequestId: $pullRequestId, mergeMethod: SQUASH}) {
                  pullRequest {
                    autoMergeRequest {
                      enabledAt
                    }
                  }
                }
            }`;

            const variables = {
              pullRequestId: context.payload.pull_request.node_id,
            }
            const result = await github.graphql(mutation, variables)
            console.log(result.actor)
            console.log(result.pullRequest)
