name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:

  context:
    name: Context
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: sleep 30
